### PR TITLE
Fix project bag

### PR DESCRIPTION
**Pull request by derkach9**

### CODE REVIEW

**Comment by andrii-s-shpitser-lpnu-ua** [comment]
What task this PR is for?

**Comment by derkach9** [comment]
This is task №5 . Fix project bag .

**Comment by andrii-s-shpitser-lpnu-ua** [comment]
image

**Comment by derkach9** [comment]
Sorry , I confused the task , it's 6 task . Maybe I'll close this pull and make a new one ?

**Comment by andrii-s-shpitser-lpnu-ua** [comment]
You can create in paralel onother one

**Review by andrii-s-shpitser-lpnu-ua — APPROVED** [review]

**Pull request merged**
